# This is a basic workflow to help you get started with Actions

name: Greeting from LAM SIU FUNG
on: push
jobs:
my-job:
  name: My Job
  runs-on: ubuntu-latest
  steps:
  - name: Print a greeting
  env:
  MY_VAR: Hi there! My name is
  FIRST_NAME: LAM
  MIDDLE_NAME: SIU
  LAST_NAME: FUNG
  run: 
echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
